-- ============================================================
-- Portfolio DB Schema (MySQL)
-- Use: mysql -u root -p portfolio < Backend/sql/schema.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contact_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  location_text VARCHAR(160) NOT NULL,
  map_embed_url VARCHAR(1200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  role VARCHAR(160) NULL,
  rating TINYINT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS visits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(120) NULL,
  page VARCHAR(255) NULL,
  time_spent BIGINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS uploaded_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  owner_type VARCHAR(30) NULL,
  file_name VARCHAR(255) NULL,
  mime_type VARCHAR(120) NOT NULL,
  file_data LONGBLOB NOT NULL,
  byte_size INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(20) NOT NULL DEFAULT 'web',
  category_label VARCHAR(60) NULL,
  title VARCHAR(180) NOT NULL,
  tech VARCHAR(220) NULL,
  description TEXT NOT NULL,
  image_url VARCHAR(500) NULL,
  image_id INT NULL,
  live_demo_url VARCHAR(500) NULL,
  github_url VARCHAR(500) NULL,
  linkedin_url VARCHAR(500) NULL,
  video_url VARCHAR(500) NULL,
  extra_label VARCHAR(80) NULL,
  extra_url VARCHAR(500) NULL,
  is_featured TINYINT NOT NULL DEFAULT 1,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  summary TEXT NOT NULL,
  content LONGTEXT NULL,
  image_url VARCHAR(500) NULL,
  image_id INT NULL,
  read_more_url VARCHAR(500) NULL,
  github_url VARCHAR(500) NULL,
  linkedin_url VARCHAR(500) NULL,
  video_url VARCHAR(500) NULL,
  extra_label VARCHAR(80) NULL,
  extra_url VARCHAR(500) NULL,
  is_published TINYINT NOT NULL DEFAULT 1,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS about_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tagline VARCHAR(220) NOT NULL,
  headline VARCHAR(220) NOT NULL,
  paragraph_1 TEXT NOT NULL,
  paragraph_2 TEXT NULL,
  paragraph_3 TEXT NULL,
  experience_summary VARCHAR(160) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS about_experiences (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year_label VARCHAR(60) NOT NULL,
  company_name VARCHAR(160) NOT NULL,
  job_role VARCHAR(160) NOT NULL,
  position_title VARCHAR(160) NOT NULL,
  description TEXT NULL,
  display_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
